import type { Metadata } from "next";
import { Hubot_Sans, IBM_Plex_Mono } from "next/font/google";
import "../styles/globals.css";

const hubotSans = Hubot_Sans({
  variable: "--font-heading",
  subsets: ["latin"],
});

const ibmMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-body",
  weight: ['400', '500', '600'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hubotSans.variable} ${ibmMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
